# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- task: Npm@1
  displayName: "Install Dependencies"
  inputs:
    command: "custom"
    customCommand: "install --no-optinal"
  
- task: Npm@1
  displayName: "Build App"
  inputs:
    workingDir: "./"
    command: "custom"
    # customCommand: "run-script build --verbose"
    customCommand: "start"

- task: CopyFiles@2
  displayName: Copy build output
  inputs:
    sourceFolder: "./build"
    contents: "**/*"
    targetFolder: '$(Build.ArtifactStagingDirectory)\build'
    cleanTargetFolder: true

- task: ArchiveFiles@2
  displayName: Archive build output
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)\build'
    archiveType: "zip"
    archiveFile: '$(Build.ArtifactStagingDirectory)\build.zip'
    includeRootFolder: false

- task: PublishBuildArtifacts@1
  displayName: Publish Build Artifacts
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)\build.zip'
